dist: xenial
language: crystal

crystal:
  - latest

stages:
  - script
  - name: before_deploy
    if: branch = master
  - name: deploy
    if: branch = master

script:
  - crystal build src/passgen.cr --release --static --cross-compile --target "x86_64-unknown-linux-gnu"
  - tar czf genpass-x86_64-unknown-linux-gnu.tar passgen

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Andrea Tupini"
  - git config --local user.email "tupini07@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$GH_KEY"
  file: "genpass-x86_64-unknown-linux-gnu.tar"
  cleanup: false


# Uncomment the following if you'd like Travis to run specs and check code formatting
# script:
#   - crystal spec
#   - crystal tool format --check
